version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    commit-message:
      prefix: "依存関係"
      include: "scope"
    groups:
      npm-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
      npm-minor-and-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:30"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    commit-message:
      prefix: "依存関係"
      include: "scope"
    groups:
      github-actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
